# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - maghrebailapp

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://sampleappaoaichatgpt.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_7ec3682a9f3244dab1f0381cdccfb0cf }}
        password: ${{ secrets.AzureAppService_ContainerPassword_eb5bfad7af17489ba1d89374c08bc1be }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: sampleappaoaichatgpt.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_7ec3682a9f3244dab1f0381cdccfb0cf }}/sample-app-aoai-chatgpt:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'maghrebailapp'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_704c4ced4fc542e58ae2645c1109eb3e }}
        images: 'sampleappaoaichatgpt.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_7ec3682a9f3244dab1f0381cdccfb0cf }}/sample-app-aoai-chatgpt:${{ github.sha }}'